from dotenv import load_dotenv
import os

load_dotenv()

INSTAGRAM_USERNAME = os.getenv("INSTAGRAM_USERNAME")
INSTAGRAM_PASSWORD = os.getenv("INSTAGRAM_PASSWORD")
INSTAGRAM_SESSION_ID = os.getenv("INSTAGRAM_SESSION_ID")

AIRTABLE_API_KEY = os.getenv("AIRTABLE_API_KEY")
AIRTABLE_BASE_ID = os.getenv("AIRTABLE_BASE_ID")
AIRTABLE_EVENTS_TABLE_ID = os.getenv("AIRTABLE_EVENTS_TABLE_ID")
AIRTABLE_USERS_TABLE_ID = os.getenv("AIRTABLE_USERS_TABLE_ID")
AIRTABLE_CALENDAR_VIEW_NAME = os.getenv("AIRTABLE_CALENDAR_VIEW_NAME")
