name: Run Scripts

on:
  #   schedule:
  #     # Runs at 8:00 AM UTC every day
  #     - cron: "0 8 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          if ! command -v poetry &>/dev/null; then
            curl -sSL https://install.python-poetry.org | python3 -
          fi

      - name: Cache Virtual Environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run Instagram Script
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_SESSION_ID: ${{ secrets.INSTAGRAM_SESSION_ID }}

        run: |
          poetry run python instagram.py
