name: Instagram Script

on:
  schedule:
    - cron: "24 13 * * 3" # Wednesday 1:24 PM UTC | 8:24 AM EST | 9:24 AM EDT
  workflow_dispatch:
    inputs:
      use_live_account:
        description: "Post to the live Rally4Israel Instagram account?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ github.event.inputs.use_live_account }}" = "yes" ]; then
            echo "INSTAGRAM_SESSION_ID=${{ secrets.INSTAGRAM_SESSION_ID }}" >> $GITHUB_ENV
          else
            echo "INSTAGRAM_SESSION_ID=${{ secrets.TEST_INSTAGRAM_SESSION_ID }}" >> $GITHUB_ENV
          fi

      - name: Run Instagram Script
        env:
          INSTAGRAM_SESSION_ID: ${{ env.INSTAGRAM_SESSION_ID }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_EVENTS_TABLE_ID: ${{ secrets.AIRTABLE_EVENTS_TABLE_ID }}
          AIRTABLE_USERS_TABLE_ID: ${{ secrets.AIRTABLE_USERS_TABLE_ID }}
          AIRTABLE_CALENDAR_VIEW_NAME: ${{ secrets.AIRTABLE_CALENDAR_VIEW_NAME }}
        run: |
          poetry run python -m r4ilpy.instagram
