name: Instagram Script

on:
  workflow_dispatch:
    inputs:
      use_live_account:
        description: "Post to the live Rally4Israel Instagram account?"
        required: true
        type: choice
        options:
          - yes
          - no
        default: "no"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.use_live_account }}" = "yes" ]; then
            echo "INSTAGRAM_SESSION_ID=${{ secrets.INSTAGRAM_SESSION_ID }}" >> $GITHUB_ENV
            echo "INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}" >> $GITHUB_ENV
          else
            echo "INSTAGRAM_USERNAME=${{ secrets.TEST_INSTAGRAM_USERNAME }}" >> $GITHUB_ENV
          fi

      - name: Run Instagram Script
        env:
          INSTAGRAM_SESSION_ID: ${{ env.INSTAGRAM_SESSION_ID }}
          INSTAGRAM_USERNAME: ${{ env.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          poetry run python -m r4ilpy.instagram
